version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend" # Location of package manifests.
    schedule:
      interval: "monthly"
# Group Dependabot updates into one single PR
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/backend" # Location of package manifests.
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
# Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
